### ISSUE TITLE
Support for multiple base64 strings

### ISSUE THREAD

**Issue by adammoisa** [j0x0j/base64-string-s3#2]
If we have multiple pdf base64 strings, we should be able to send an array. Any idea's how to do this or if you will support it?

**Comment by j0x0j** [comment]
In order to upload multiple base64 strings, I would suggest you create a `putter` instance for each one, no plans to support multiple strings, I would also recommend you do this serially for if you have too many b64 strings in memory you'll probably hit a heap limit (~1.7gb is the max). The idea here is to limit the amount of buffers your application has in memory at a given time. 

Although if your strings are relatively small, you could loop through the array and instantiate a `putter` in each iteration. I think something like this might work:

```js
const options = {}
const strings = ['/9j/4QAYRXhpZg...', '...']

let jobs = 0

strings.forEach((str, i) => {
  const putter = new Putter(options)
  putter.put(str, `images/success_${i}.jpg`, 'image/jpeg', 'public-read')
  putter.on('progress', data => {
    console.log(`progress for ${i}`, data)
  })
  putter.on('response', data => {
    console.log(`response for ${i}`, data)
    jobs-=1
    if (jobs === 0) // your done
  })
  jobs+=1
})
```
